### ISSUE TITLE
Why are the WRF output files vtk format?

### ISSUE THREAD

**Issue by lj-cug** [kaust-vislab/Inshimtu-basic#1]
The WRF output file format is usually NetCDF4. Why are the used WRF data file VTK format ?

**Comment by jameskress** [comment]
These are simply example files meant to exercise different parts of the pipeline. The original wrf files were NetCDF, the VTK files were converted from NetCDF, but as you know, these files are very large and have lots of data we don't need for visualization. So not worth storing in a git repo for example purposes.
